# Generated by Django 5.1.4 on 2025-01-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rating', models.FloatField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('room_type', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('image_path', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyReview',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='property_rewriter.scrapedproperty')),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySummary',
            fields=[
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='property_rewriter.scrapedproperty')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
