version: '3.8'

services:
  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      test-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://test_user:test_password@test-db:5432/test_db
    command: ["pytest", "--cov=main", "--cov-report=term-missing"]